### ISSUE TITLE
Met@10.1.1 does not compile on macos using apple clang 14.0.3

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#615]
**Describe the bug**

When building met@10.1.1 using either x86_64 or arm64 architecture, and Clang version 14.0.3, the compile fails with the following message:
```
tc_rmw.cc:587:13: error: no viable conversion from 'ConcatString' to 'std::vector<std::string>::value_type' (aka 'std::string')
            data_info->level_attr());
            ^~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:823:35: note: candidate constructor not viable: no known conversion from 'ConcatString' to 'const std::string &' for 1st argument
    _LIBCPP_CONSTEXPR_AFTER_CXX17 basic_string(const basic_string& __str);
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:841:5: note: candidate constructor template not viable: no known conversion from 'ConcatString' to 'const char *' for 1st argument
    basic_string(const _CharT* __s) : __r_(__default_init_tag(), __default_init_tag()) {
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:816:66: note: explicit constructor is not a candidate
    _LIBCPP_HIDE_FROM_ABI _LIBCPP_CONSTEXPR_AFTER_CXX17 explicit basic_string(const allocator_type& __a)
                                                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/string:881:18: note: explicit constructor is not a candidate
        explicit basic_string(const _Tp& __t);
                 ^
../../../../src/basic/vx_log/concat_string.h:148:7: note: candidate function
      operator const std::string () const;
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:584:89: note: passing argument to parameter '__x' here
    _LIBCPP_CONSTEXPR_AFTER_CXX17 _LIBCPP_INLINE_VISIBILITY void push_back(value_type&& __x);
                                                                                        ^
1 error generated.
```

Any thoughts? Thanks!

**To Reproduce**

I have tried this on both x86_64 (Rosetta emulation) and arm64 with GNU Fortran 12.2.0, Clang 14.0.3, MacOS Ventura 13.4 which gives the same failure on both systems. If I back up Clang to 14.0.0 the build completes successfully.

I've also tried doing the build with the latest met@11.0.1 with the same error.

**Expected behavior**

The met@10.1.1 build completes successfully.

**System:**

MacOS ventura 13.4, either x86_64 (Rosetta) or arm64 architecture.

**Additional context**

I also tried adding `-std=c++17` compiler flag and this didn't help.

**Comment by mathomp4** [comment]
I really wish Apple would provide release notes on what they change in Apple Clang. Sometimes it seems like patch number releases break all sorts of stuff.

I have never seen this error in my testing, but I don't do a lot of C++.

I suppose my next thought would be to try using `-std=gnu++17`? Maybe this is a GNU extension to C++? I believe the "default" for Apple Clang is `gnu++14`.

**Comment by srherbener** [comment]
@mathomp4 thanks for the feedback! I hadn't thought of the GNU extensions. I already tried `-std=c++17` and I just tried `-std=gnu++17` and both didn't help.
