### PR TITLE
Update site configs for hercules / orion / ursa

### LINKED ISSUE #1471: Installation issue: py-scipy / spack-stack @ develop fails to configure with oneAPI @ 2024.2.1 on hercules and orion
**Describe the issue**

`py-scipy` fails to configure / build / install when spec'd for `oneAPI @ 2024.2.1` for `spack-stack @ develop` (updated with two PRs)

`py-scipy @ 1.14.1` spec: [py-scipy.spec.txt](https://github.com/user-attachments/files/18552632/py-scipy.spec.txt)

This failure prevents a `unified-dev` env from building / installing.

Pertinent error output:
- [log.install.txt](https://github.com/user-attachments/files/18552595/log.install.txt)
- [build-stage.txt](https://github.com/user-attachments/files/18552489/build-stage.txt)

The failure appears identical to that which is reported in [Installation issue: py-scipy@1.14 with Intel Classic compilers #48243](https://github.com/spack/spack/issues/48243) and fixed in [Add conflict for py-scipy@1.14: with Intel Classic #48251](https://github.com/spack/spack/pull/48251), despite that PR being applied.

**To Reproduce**

`spack-stack @ develop` with changes incorporated from:

[Avoid linking to libirc.so in spack (parallel-netcdf), turn off crypt variant for Python, and update Orion site config to fix tar issue #1435](https://github.com/JCSDA/spack-stack/pull/1435)

and

[Bug fix in parallel-netcdf to avoid linking to libirc.so AND cherry-pick spack develop PR 48251 (conflict Intel Classic with scipy@1.14) #495](https://github.com/JCSDA/spack/pull/495). 

The fix from [Add conflict for py-scipy@1.14: with Intel Classic #48251](https://github.com/spack/spack/pull/48251) is already present in the **JCSDA** `spack` specified in `spack-stack @ develop / .gitmodules`  -- the `build-stage` output clearly shows that a valid `oneAPI` compiler is found.

Configuration files:

- `site-compilers.yaml` [site-compilers.yaml.txt](https://github.com/user-attachments/files/18552490/site-compilers.yaml.txt)
- `site-packages_oneapi.yaml` [site-packages_oneapi.yaml.txt](https://github.com/user-attachments/files/18552492/site-packages_oneapi.yaml.txt)
- `site-packages.yaml` [site-packages.yaml.txt](https://github.com/user-attachments/files/18552493/site-packages.yaml.txt)

- `common-packages_oneapi.yaml` [common-packages_oneapi.yaml.txt](https://github.com/user-attachments/files/18552495/common-packages_oneapi.yaml.txt)
- `common-packages.yaml` [common-packages.yaml.txt](https://github.com/user-attachments/files/18552496/common-packages.yaml.txt)

**Expected behavior**

`py-scipy` configures, builds, and installs with `oneAPI @ 2024.2.1` compilers (as a preface to `spack-stack @ release/1.9.0`)

**System:**

tier1 **EPIC** hosts **hercules** (`linux-rocky9-icelake`) and **orion** (`linux-rocky9-skylake_avx512`)

**Additional context**

A test env to install only `py-scipy % gcc` (and dependencies) successfully configures / builds / installs.

`py-scipy @ 1.14.1 % gcc` spec: [py-scipy-spec.gcc.txt](https://github.com/user-attachments/files/18552806/py-scipy-spec.gcc.txt)

Given this success, I'm unclear if something is misconfigured or if this is a bug somewhere.

### LINKED ISSUE #1900: Ursa: undefined reference in spack-stack/2.0.0 ecmwf-atlas-0.44.1
## Description

The GDASApp build on Ursa using spack-stack/2.0.0 fails with
```
3.31.8-lowbhqn/bin/cmake -E cmake_link_script CMakeFiles/saber_quench_error_covariance_toolbox.x.dir/link.txt --verbose=YES
/usr/bin/ld: /contrib/spack-stack/spack-stack-2.0.0/envs/ue-oneapi-2025.2.1/install/intel-oneapi-compilers/2025.2.1/ecmwf-atlas-0.44.1-f26wo7d/lib64/libatlas.so.0.44: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
```

## To Reproduce

1. clone [GDASApp](https://github.com/NOAA-EMC/GDASApp) 
2. `git checkout feature/ss200`
3. execute `./build.sh -t ursa -vf > log.build 2>&1 &`

When the build fails, search the log file for the above error

## Expected behavior

GDASApp should build with spack-stack/2.0.0

## System, compiler, code, ...

System:  Ursa
Compiler information from `log.build`
```
-- The C compiler identification is IntelLLVM 2025.2.1
-- The CXX compiler identification is IntelLLVM 2025.2.1
-- The Fortran compiler identification is IntelLLVM 2025.2.1
```

## Additional context

The upgrade of GDASApp to spack-stack/2.0.0 is being documented in GDASApp issue [#2057](https://github.com/NOAA-EMC/GDASApp/issues/2057).

### PR DESCRIPTION
**Pull request by rickgrubin-noaa**
## Description

Update site configs for **_hercules_**, **_orion_**, and **_ursa_** for `release/2.1`

- hercules
  - `oneapi`: use EPIC-installed compilers
  - `gcc`: update `mpi` external spec to address concretizer requirements 
- orion
  - `oneapi`: use EPIC-installed compilers
- ursa
  - remove references to unnecessary paths / rpaths

### Dependencies

None

### Issues addressed

- Resolves #1900 
- Resolves #1471 (already closed)

### Applications affected

GDASapp, UFS-WM

### Systems affected

- hercules
- orion
- ursa

## Testing

- CI: _Note whether the automatic tests (GitHub actions tests that run automatically for every commit) pass or not_
    - [ ] GitHub actions CI tests pass
    - [ ] GitHub actions CI tests do not pass (_provide explanation_)
    - [x] GitHub actions CI tests skipped (_provide explanation if necessary_)
- New tests added: _List and describe any new tests added to GitHub actions_
    - [ ] ...
- Additional testing: _Add information on any additional tests conducted_
    - [x] GDASapp builds / successfully runs ctests (see #1900)
    - [x] UFS-WM builds with appropriate modulefile changes; not yet regression tested

## Checklist

- [x] This PR addresses one issue/problem/enhancement or has a very good reason for not doing so.
- [x] These changes have been tested on the affected systems and applications.
- [x] All dependency PRs/issues have been resolved and this PR can be merged.
- [x] All necessary updates to the documentation ([spack-stack wiki](https://github.com/jcsda/spack-stack/wiki)) will be made when this PR is merged

### CODE REVIEW

**Review by climbfuji — APPROVED** [review]
That looks great, much simpler!

**Comment by climbfuji** [comment]
I can merge this w/o testing after #1887

**Review by RatkoVasic-NOAA — APPROVED** [review]
LGTM
