### ISSUE TITLE
spack-stack does not build on MacOS Sonoma with Command Line Tools 15.x

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1249]
**Describe the bug**

First of all, I think we are okay with MacOS versions earlier that Sonoma (such as Ventura with Command Line Tools 14.x) so this issue is limited to Sonoma.  For example the spack-stack CI tests building on MacOS Ventura with Command Line Tools 14.x - apple-clang 14.0.3).

I've tried two configurations so far:
- Sonoma 14.6.1, Command Line Tools 15.1
   In this case musl fails to build, and I'm seeing make errors like this:
```
 >> 193    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 194    make[1]: *** [lib/autotest/autotest.m4f] Error 1
     195    make[1]: *** Waiting for unfinished jobs....
  >> 196    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 197    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 198    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 199    make[1]: *** [lib/autoconf/autoconf.m4f] Error 1
  >> 200    make[1]: *** [tests/wrapper.in] Error 1
  >> 201    make[1]: *** [lib/m4sugar/m4sugar.m4f] Error 1
  >> 202    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 203    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 204    make[1]: *** [lib/m4sugar/m4sh.m4f] Error 1
  >> 205    make: *** [all] Error 2
```

- Sonoma 14.6.1, Command Line Tools 15.3
   In this case autoconf fails to build with the following cmake  error:
```
  >> 193    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 194    make[1]: *** [lib/autotest/autotest.m4f] Error 1
     195    make[1]: *** Waiting for unfinished jobs....
  >> 196    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 197    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 198    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 199    make[1]: *** [lib/autoconf/autoconf.m4f] Error 1
  >> 200    make[1]: *** [tests/wrapper.in] Error 1
  >> 201    make[1]: *** [lib/m4sugar/m4sugar.m4f] Error 1
  >> 202    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 203    autom4te: error: need GNU m4 1.4 or later: /usr/bin/m4
  >> 204    make[1]: *** [lib/m4sugar/m4sh.m4f] Error 1
  >> 205    make: *** [all] Error 2
```

**To Reproduce**
On a Somoma MacOS, follow instructions to build spack-stack using the latest develop branches from JCSDA/spack-stack and JCSDA/spack

**Expected behavior**

The spack-stack build completes successfully

**System:**
What system(s) are you running the code on?
Somona 14.6.1, Command Line tools 15.1
Somona 14.6.1, Command Line tools 15.3

**Additional context**

**Comment by srherbener** [comment]
I think the reported issues could be addressed by installing the homebrew versions of m4. Would this be a proper way to handle this?

I'm going to forge ahead with brew install of m4 on the Command Line Tools 15.3 case and see if that helps.

**Comment by srherbener** [comment]
Just discovered that my installation of Command Line Tools 15.3 was corrupt, which was impacting m4. I'm going to start over with a fresh slate.

**Comment by climbfuji** [comment]
Regarding musl. You need to use an external libiconv as provider for iconv. I explained this previously, but the old libc is no longer allowed as provider for iconv, glibc has a conflict with apple-clang/darwin, and neither musl nor libiconv build on macOS with apple-clang. External libiconv from homebrew fixes this.

About m4, I have clang version 15.0.0 on sonoma 14.4 and that works (builds m4). If your external m4 approach works, that's great, otherwise I'd stay away from 15.3 and use 15.0 or 15.1 with external libiconv.

**Comment by srherbener** [comment]
> Regarding musl. You need to use an external libiconv as provider for iconv. I explained this previously, but the old libc is no longer allowed as provider for iconv, glibc has a conflict with apple-clang/darwin, and neither musl nor libiconv build on macOS with apple-clang. External libiconv from homebrew fixes this.
> 
> About m4, I have clang version 15.0.0 on sonoma 14.4 and that works (builds m4). If your external m4 approach works, that's great, otherwise I'd stay away from 15.3 and use 15.0 or 15.1 with external libiconv.

I have tried using the homebrew libiconv (buildable: false)  but I couldn't get spack-stack to stop trying to build musl. I don't think I was on the exact Sonoma 14.4 version (might have been 14.4.1 or .2) so perhaps that was the issue. Is there a way to back up Sonoma?

**Comment by climbfuji** [comment]
Did you set the provider for iconv to libiconv?

I don't know how to back up Sonoma and I wouldn't go there, probably way more complicated than convincing spack to use libiconv.

**Comment by srherbener** [comment]
I'm pretty sure I had the provider for iconv set to libiconv, but I can double check that when I'm rebuilding.

It looks like my m4 (/usr/bin/m4) is corrupt - it won't run when I try `mv --version`.  I'm going to try the homebrew m4 first.

**Comment by srherbener** [comment]
For the musl issue, I have this in my spack.yaml
```
packages:
    all:
      prefer: ['%apple-clang']
      compiler:
      - apple-clang@15.0.0
      providers:
        mpi: [openmpi@5.0.3]
        iconv: [libiconv]
    ewok-env:
      variants: +mysql
```
But concretize still shows musl as a package to be built. musl is listed as a dependency of gettext and libxm2. I suppose I could homebrew install these and use them as external packages.  I'm only seeing this issue with Command Line Tools 15.1. Command line tools 15.3 ended up without musl (even without specifying libiconv as the provider of iconv).

At this point 15.3 is offering less resistance, after using homebrew m4, and I'll keep pursuing 15.3 for now. The install is still running.

**Comment by climbfuji** [comment]
Weird. I wonder if double colons would help

**Comment by srherbener** [comment]
I agree that this is weird. There has been a lot of weirdness with the Mac lately.

What do the double colons do?

**Comment by srherbener** [comment]
My build on 15.3 got quite far (294 out of 318 packages). I'm now seeing this with eckit:
```
In file included from /Users/steveherbener/spack-stack/cache/build_stage/spack-stage-eckit-1.       24.5-zc5kjgjtnonxnsrienad3dpnbdqpavr4/spack-src/src/eckit/system/ResourceUsage.cc:15:
205029 /Users/steveherbener/spack-stack/cache/build_stage/spack-stage-eckit-1.24.5-zc5kjgjtnonxnsrienad3dpnbdqpavr4/spack-src/src/eckit/system/ResourceUsage.h:30:5: error: unknown type name 'size_t'
205030     size_t maxResidentSetSize() const;
205031     ^
205032 /Users/steveherbener/spack-stack/cache/build_stage/spack-stage-eckit-1.24.5-zc5kjgjtnonxnsrienad3dpnbdqpavr4/spack-src/src/eckit/system/ResourceUsage.h:32:5: error: unknown type name 'size_t'
205033     size_t numberOfSwaps() const;
205034     ^
205035 /Users/steveherbener/spack-stack/cache/build_stage/spack-stage-eckit-1.24.5-zc5kjgjtnonxnsrienad3dpnbdqpavr4/spack-src/src/eckit/system/ResourceUsage.h:43:5: error: unknown type name 'size_t'
205036     size_t factor_;
205037     ^
```
Looks like size_t is not defined in the global namespace. Not sure why this changed.

**Comment by srherbener** [comment]
This error was fixed in eckit@1.25.0 (and newer) releases: https://github.com/ecmwf/eckit/pull/93

What is the appropriate way to deal with this for the 1.8.0 release?
- Move to eckit 1.25.0 (or newer) for all platforms - ie, update the eckit require spec in common/packages.py
- Have macos only instructions say to change the eckit version in common/packages.py to 1.25.0

**Comment by climbfuji** [comment]
I suggest updating to eckit@1.25 unless there is a good reason not to do so
