### ISSUE TITLE
Update eckit and atlas versions for JEDI

### ISSUE THREAD

**Issue by fmahebert** [JCSDA/spack-stack#567]
**Is your feature request related to a problem? Please describe.**

As followup from the JCSDA atlas-related code sprint, we should update the eckit and atlas versions to bring in recent bugfixes and new functionality needed by JEDI. I will update this issue when the eckit and atlas PRs are merged and tags are known.

**Comment by climbfuji** [comment]
Thanks for letting us know. Please provide the new versions by May 12, if possible, but no later than May 16. Thanks!

**Comment by climbfuji** [comment]
@fmahebert It's May 12, have you heard anything about the new tags?

Note that there was also a discussion in one of the UK MetOffice repos about a hard requirement for C++-17 standard since May 3 in atlas. We need to take this into account, since this may throw a wrench into rolling out a new version or at cause delays.

Thanks!

**Comment by fmahebert** [comment]
@climbfuji I'm still iterating on the PRs with the ECMWF devs. Doing my best, but we may or may not get tags by the 16th...

**Comment by climbfuji** [comment]
Ok, keep me posted please. We should test building the head of ecmwf-atlas on the spack-stack tier-1 platforms at least in the meanwhile

**Comment by shlyaeva** [comment]
The eckit changes were merged a few hours ago, although the tag wasn't created yet. 
https://github.com/ecmwf/eckit/commit/046ffb1597a619fd873b6bae4af1150a1beec62a is the commit that we'd like to use and should ask ecmwf folks to create the tag for. (cc @ytremolet).

Atlas changes aren't merged yet.

**Comment by climbfuji** [comment]
We have come up with a workaround to get this eckit commit and the atlas changes (without strict C++-17 requirements) into spack-stack-1.4.0.

**Comment by climbfuji** [comment]
Well, not so fast. eckit and atlas build fine in spack-stack, but then I get this when I build jedi-bundle:
```
/Users/heinzell/work/spack-stack-update-eckit-atlas/envs/unified-env/install/apple-clang/13.1.6/ecmwf-atlas-0.33.1-pre-jcsda-zp627ox/include/atlas/array/native/NativeArrayView.h:60:
/Users/heinzell/work/spack-stack-update-eckit-atlas/envs/unified-env/install/apple-clang/13.1.6/ecmwf-atlas-0.33.1-pre-jcsda-zp627ox/include/atlas/array/LocalView.h:105:66: error: no template named 'is_convertible_v' in namespace 'std'; did you mean 'is_convertible'?
    template <typename ValueTp, typename = std::enable_if_t<std::is_convertible_v<ValueTp*, Value*>>>
                                                            ~~~~~^~~~~~~~~~~~~~~~
                                                                 is_convertible
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/type_traits:1728:61: note: 'is_convertible' declared here
template <class _T1, class _T2> struct _LIBCPP_TEMPLATE_VIS is_convertible
```
I've seen this before when mixing c++-14 and c++-17.

**Comment by fmahebert** [comment]
> ecmwf-atlas-0.33.1-pre-jcsda-zp627ox

Does this spack path mean the tag in use is `0.33.1-pre-jcsda`? If so, this failure is expected... could you try `0.33.1-pre-jcsda-cxx14` instead? Else, I'm not sure what's going on..

Probably not relevant: I've found some more cxx17 in the atlas tests, but for some reason this isn't causing any problem. Must be getting compiled as cxx17 in atlas, and of course is never compiled from jedi. I don't understand our build system... I'm building atlas in my bundle, so different bundle repos are allowed different cxx standards?? 😵

**Comment by climbfuji** [comment]
I can compile with `0.33.1-pre-jcsda-cxx14`. I am seeing many warnings, presumably the same that you saw:
```
In file included from /Users/heinzell/work/spack-stack-update-eckit-atlas/jedi-bundle/jedi-bundle/ufo/src/ufo/ObsBiasCovariance.cc:23:
In file included from /Users/heinzell/work/spack-stack-update-eckit-atlas/jedi-bundle/build-release/ioda/include/ioda/ObsSpace.h:38:
In file included from /Users/heinzell/work/spack-stack-update-eckit-atlas/jedi-bundle/build-release/ioda/include/ioda/distribution/Distribution.h:16:
In file included from /Users/heinzell/work/spack-stack-update-eckit-atlas/envs/unified-env/install/apple-clang/13.1.6/eckit-1.23.1-pre-26ncroe/include/eckit/geometry/Point2.h:6:
/Users/heinzell/work/spack-stack-update-eckit-atlas/envs/unified-env/install/apple-clang/13.1.6/eckit-1.23.1-pre-26ncroe/include/eckit/geometry/KPoint.h:23:16: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace eckit::geometry {
               ^~~~~~~~~~
                { namespace geometry
```
As long as we "can live" with these warnings (or use a workaround, see below) until we update everything to C++17 in the next quarter, we should be ok.

One workaround: newer compilers support an option to suppress these warnings. According to https://stackoverflow.com/questions/42809803/how-to-silence-gcc-warning-against-c17-features, `gcc@12` and `clang@12` understand `-Wno-c++17-extensions`. I ran my `cmake` command for jedi-bundle like this:
```
cmake -DCMAKE_CXX_FLAGS="-Wno-c++17-extensions" ../jedi-bundle 2>&1 | tee log.ecbuild
```
and that seemed to do the trick. Since the workaround would need to be only short-lived, and not buried somewhere in our build system (increases the danger to not remember it and letting things go), we could just tell people to add this for now?

**Comment by ytremolet** [comment]
Is c++17 needed only for atlas or also for eckit? For eckit I hope we'll get a tag today and we can include it in the stack so we might have to deal with the c++17 question. For atlas, we are working actively on it at the moment. I'm quite sure that whatever we put in the stack this week will already be outdated by the time we get to the release at the end of June. So regardless of what we do, it's not going to be used much.

Active repos should be in our bundles, not in the stack. That's true for eckit and atlas but also crtm.

**Comment by climbfuji** [comment]
eckit has C++-17 headers and you get warnings if you compile with C++-14 std, but no errors. For atlas, it's a hard requirement unless we use @fmahebert's branch above that is based on the C++-14 version.

There is no time to update the entire software stack to C++-17 this week (this includes updating boost and other packages) for the spack-stack-1.4.0 release. eckit will still be ok, as long as we can live with the warnings, and atlas is ok if we use Francois' branch in spack for now.

We can do whatever we want in the bundles and ignore the version coming from the stack ... there just needs to be one so that we continue to make sure it builds and works.

**Comment by shlyaeva** [comment]
I would go with updating eckit version (and living with warnings since there are no errors) and keeping the older atlas version. For atlas it sounds like we'll likely have to update it via bundle before the next spack-stack release anyway, so my tendency would be to not do extra work for spack-stack release now.

**Comment by climbfuji** [comment]
Closing this. Please open a new issue when the C++-17 issues with newer eckit, fckit, ecmwf-atlas are sorted out. We'll then put the libraries in the next spack-stack release (presumably 1.5.0).
