### ISSUE TITLE
GDASApp compilation failure using Ursa spack-stack/2.1.0

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [JCSDA/spack-stack#1948]
## Description

When GDASApp is compiled on Ursa using spack-stack/2.1.0, the build aborts on `fv3-jedi-lm/src/dynamics/atmos_cubed_sphere/model/fv_arrays_nlm.F90` with the following error messages:
```
/scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/ursa/ss200/sorc/gdas.cd/bundle/fv3-jedi-lm/src/dynamics/atmos_cubed_sphere/model/fv_arrays_nlm.F90(23): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FMS_IO_MOD]
  use fms_io_mod,            only: restart_file_type
------^
/scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/ursa/ss200/sorc/gdas.cd/bundle/fv3-jedi-lm/src/dynamics/atmos_cubed_sphere/model/fv_arrays_nlm.F90(588): error #6457: This derived type name has not been declared.   [RESTART_FILE_TYPE]
     type(restart_file_type) :: BCfile_ne, BCfile_sw
----------^
/scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/ursa/ss200/sorc/gdas.cd/bundle/fv3-jedi-lm/src/dynamics/atmos_cubed_sphere/model/fv_arrays_nlm.F90(743): error #6457: This derived type name has not been declared.   [RESTART_FILE_TYPE]
     type(restart_file_type) :: Fv_restart, SST_restart, Fv_tile_restart, &
----------^
/scratch3/NCEPDEV/da/Russ.Treadon/git/global-workflow/ursa/ss200/sorc/gdas.cd/bundle/fv3-jedi-lm/src/dynamics/atmos_cubed_sphere/model/fv_arrays_nlm.F90(23): error #6580: Name in only-list does not exist or is not accessible.   [RESTART_FILE_TYPE]
  use fms_io_mod,            only: restart_file_type
```

## To Reproduce

1. clone GDASApp branch [feature/ss2x](https://github.com/NOAA-EMC/GDASApp/tree/feature/ss2x)
2. execute `./build.sh -v -f`

The compilation will abort with the above error messages. 

## Expected behavior

GDASApp should successfully build with spack-stack/2.1.0

## System, compiler, code, ...

The following modules are loaded as part of the failed GDASApp build on Ursa
```
Currently Loaded Modules:
  1) intel-oneapi-compilers/2025.3.1        20) netcdf-c/4.9.2        39) eigen/3.4.0                58) libxt/1.3.1           77) py-netcdf4/1.7.2
  2) stack-intel-oneapi-compilers/2025.3.1  21) nccmp/1.9.0.1         40) openblas/0.3.27            59) libxmu/1.2.1          78) py-pybind11/2.13.6
  3) intel-oneapi-mpi/2021.17.1             22) netcdf-fortran/4.6.1  41) eckit/1.32.3               60) libxpm/3.5.17         79) py-setuptools/69.2.0
  4) stack-intel-oneapi-mpi/2021.17         23) antlr/2.7.7           42) fckit/0.14.1               61) libxaw/1.0.16         80) py-pycodestyle/2.11.0
  5) intel-oneapi-mkl/2025.3                24) gsl/2.8               43) fiat/1.6.1                 62) udunits/2.2.28        81) libyaml/0.2.5
  6) glibc/2.34                             25) nco/5.3.3             44) ectrans/1.7.0              63) ncview/2.1.9          82) py-pyyaml/6.0.2
  7) cmake/3.31.8                           26) parallelio/2.6.2      45) fms/2025.03-gfs-constants  64) netcdf-cxx4/4.3.1     83) py-scipy/1.16.0
  8) pigz/2.8                               27) wget/1.21.1           46) py-mpi4py/4.0.1            65) json/3.11.3           84) py-packaging/25.0
  9) zstd/1.5.7                             28) sqlite/3.46.0         47) esmf/8.8.0                 66) rocoto/1.3.7          85) py-six/1.17.0
 10) tar/1.35                               29) util-linux-uuid/2.41  48) qhull/2020.2               67) bacio/2.6.0           86) py-python-dateutil/2.8.2
 11) gettext/0.23.1                         30) python/3.11.11        49) ecmwf-atlas/0.44.1         68) w3emc/2.13.0          87) py-pytz/2024.2
 12) nghttp2/1.65.0                         31) boost/1.84.0          50) ip/5.4.0                   69) prod_util/2.1.2       88) py-tzdata/2025.2
 13) curl/8.11.1                            32) python-venv/1.0       51) gsl-lite/0.41.0            70) jasper/4.2.4          89) py-pandas/2.3.1
 14) zlib/1.2.13                            33) py-numpy/1.26.4       52) libjpeg/3.0.4              71) g2/3.5.1              90) py-xarray/2024.7.0
 15) git/2.43.5                             34) bufr/12.1.0           53) krb5/1.21.1-1              72) grib-util/1.4.0       91) py-f90nml/1.4.3
 16) hdf5/1.14.5                            35) git-lfs/3.5.1         54) libtirpc/1.3.3             73) py-markupsafe/2.1.3   92) py-pip/25.1.1
 17) parallel-netcdf/1.12.3                 36) ecbuild/3.12.0        55) hdf/4.2.15                 74) py-jinja2/3.1.4       93) py-click/8.1.8
 18) snappy/1.2.1                           37) openjpeg/2.3.1        56) jedi-cmake/1.4.0           75) py-certifi/2025.4.26  94) py-wheel/0.45.1
 19) c-blosc/1.21.6                         38) eccodes/2.33.0        57) libpng/1.6.37              76) py-cftime/1.6.4       95) GDAS/ursa.intel
```

The build uses the following Intel compilers
```
-- The C compiler identification is IntelLLVM 2025.3.1
-- The CXX compiler identification is IntelLLVM 2025.3.1
-- The Fortran compiler identification is IntelLLVM 2025.3.0
```

## Additional context

While `modulefiles/GDAS/ursa.intel.lua` loads `fms/2025.03`, the module listing shows that `fms/2025.03-gfs-constants` is loaded.

**Comment by climbfuji** [comment]
That is expected. The newer versions of FMS have finally removed the deprecated FMS IO version 1 layer. See the FMS GitHub website and release notes. FMS IO v1 was deprecated for a year or more before they finally remove it. GDASApp needs to update their FMS IO to use the new FMS IO v2.

**Comment by RussTreadon-NOAA** [comment]
Looks like https://github.com/JCSDA-internal/fv3-jedi-linearmodel/issues/18 has been opened to address the need to update fv3-jedi-linearmodel to work with the FMS provided by spack-stack/2.x.

**Comment by climbfuji** [comment]
> Looks like [JCSDA-internal/fv3-jedi-linearmodel#18](https://github.com/JCSDA-internal/fv3-jedi-linearmodel/issues/18) has been opened to address the need to update fv3-jedi-linearmodel to work with the FMS provided by spack-stack/2.x.

Correct. `fv3-jedi` itself already uses FMS IO v2.

**Comment by RussTreadon-NOAA** [comment]
We will update the GDASApp hash for fv3-jedi-linearmodel once https://github.com/JCSDA-internal/fv3-jedi-linearmodel/issues/18 is closed.

Close this issue.
