### ISSUE TITLE
Install spack-stack 1.8.0 (and all add-on envs needed for UFS WM @ develop) with LLVM compilers on Hera

### ISSUE THREAD

**Issue by rickgrubin-noaa** [JCSDA/spack-stack#1345]
**Is your feature request related to a problem? Please describe.**

Install [spack-stack @ v1.8.0](https://github.com/JCSDA/spack-stack/tree/release/1.8.0) with `LLVM` compilers on **_hera_**

**Describe the solution you'd like**

Configure and build [spack-stack @ v1.8.0](https://github.com/JCSDA/spack-stack/tree/release/1.8.0) for `LLVM` compilers installed on **_hera_** (as noted here: [Track availability / installation of Intel oneAPI (LLVM) compilers on tier1 hosts](https://github.com/JCSDA/spack-stack/issues/1325)

**Additional context**

Build and test the [UFS WM @ branch develop](https://github.com/ufs-community/ufs-weather-model) against the installed stack.

Build with both `ifort` and `ifx` (different stacks) as the `Fortran` compiler.

**Comment by rickgrubin-noaa** [comment]
On **hera**, trying to configure `spack-stack @ release/1.8.0` for `LLVM` compilers.

For these two modules (per `module available`):

`intel/2024.2.1`  and  `impi/2024.2.1`

`configs/sites/tier1/hera/compilers.yaml`
```
compilers:
- compiler:
  spec: oneapi@2042.2.1
  paths:
   cc: /apps/oneapi/compiler/2024.2/bin/icx
   cxx: /apps/oneapi/compiler/2024.2/bin/icx
   f77: /apps/oneapi/compiler/2024.2/bin/ifx
   fc: /apps/oneapi/compiler/2024.2/bin/ifx
  flags: {}
  operating_system: rocky8
  modules:
  - intel/2024.2.1
  environment:
   prepend_path:
    PATH: '/apps/spack/linux-rocky8-x86_64/gcc-8.5.0/gcc-14.2.0-27o6emykdlx4ze3ooerg4bofx7lgn35p/bin'
    LD_LIBRARY_PATH: '/apps/spack/linux-rocky8-x86_64/gcc-8.5.0/gcc-14.2.0-27o6emykdlx4ze3ooerg4bofx7lgn35p/lib64'
    CPATH: '/apps/spack/linux-rocky8-x86_64/gcc-8.5.0/gcc-14.2.0-27o6emykdlx4ze3ooerg4bofx7lgn35p/include'
  extra_rpaths: []
```


`configs/sites/tier1/hera/packages_oneapi.yaml`
```
packages:
 all:
  compiler:: [oneapi@2024.2.1]
  providers:
   mpi:: [intel-oneapi-mpi@2021.13]
   # Remove the next three lines to switch to intel-oneapi-mkl
   blas:: [openblas]
   fftw-api:: [fftw]
   lapack:: [openblas]
 mpi:
  buildable: False
 intel-oneapi-mpi:
  externals:
  - spec: intel-oneapi-mpi@2021.13%oneapi@2024.2.1
   modules:
   - impi/2024.2.1
   prefix: /apps/oneapi
[...]
```


Choosing `mpi:: [intel-oneapi-mpi@2021.13]` because

```
% module show impi/2024.2.1
-----------------------------------------------------------------------------------------------------------------------------
  /apps/modules/modulefamilies/intel_2024.2.1/impi/2024.2.1:
-----------------------------------------------------------------------------------------------------------------------------
whatis("Name: Intel(R) MPI Library")
whatis("Version: modulefiles/2021.13")
setenv("I_MPI_ROOT","/apps/oneapi/mpi/2021.13")
```


Concretization fails as:

```
% spack concretize --force 2>&1 | tee $DIR/$ENV/log.concretize
==> Error: concretization failed for the following reasons:

  1. Attempted to use external for 'intel-oneapi-mpi' which does not satisfy any configured external spec
  2. Attempted to build package intel-oneapi-mpi which is not buildable and does not have a satisfying external
    attr('node_compiler_version_satisfies', 'intel-oneapi-mpi', 'oneapi', '2024.2.1') is an external constraint for intel-oneapi-mpi which was not satisfied
```

**hera** does provide a module named `intel-llvm/2024.2.1` (not sure why), which is functionally identical to `intel/2024.2.1` -- using it yields the same result.

Ideas / suggestions?

**Comment by rickgrubin-tomorrow** [comment]
```
compilers:
- compiler:
  spec: oneapi@_2042_.2.1
```

Oops.

Corrected typo yields a concretized env; fails to build `sfcio@1.4.1` with `ifx`.

**Comment by RatkoVasic-NOAA** [comment]
> ```
> compilers:
> - compiler:
>   spec: oneapi@_2042_.2.1
> ```
> 
> Oops.
> 
You are not planning to retire before 2042?

**Comment by rickgrubin-noaa** [comment]
> > ```
> > compilers:
> > - compiler:
> >   spec: oneapi@_2042_.2.1
> > ```
> > 
 
> > Oops.
> 
> You are not planning to retire before 2042?

Might be dead and gone by then!

**Comment by rickgrubin-tomorrow** [comment]
As of Monday November 04: using `ifx` as the Fortran compiler, bumped versions for

- `gfsio` --> `1.4.2`
- `landsfcutil` --> `2.4.2`
- `sfcio` --> `1.4.2`

as release notes for each state: "**_adds Intel oneAPI support_**" and each successfully built. 

Failing in `cdo`:
```
Bitrounding.cc:81:18: error: no member named 'clamp' in namespace 'std'
   81 |   int nsb = std::clamp(keepMantissaBits, 1, 23);
      |             ~~~~~^
Bitrounding.cc:415:36: error: no member named 'clamp' in namespace 'std'
  415 |                         nsb = std::clamp(nsb, params.minBits, params.maxBits);
      |                               ~~~~~^

```

**Comment by rickgrubin-tomorrow** [comment]
> Failing in `cdo`:
> 
> ```
> Bitrounding.cc:81:18: error: no member named 'clamp' in namespace 'std'
>    81 |   int nsb = std::clamp(keepMantissaBits, 1, 23);
>       |             ~~~~~^
> Bitrounding.cc:415:36: error: no member named 'clamp' in namespace 'std'
>   415 |                         nsb = std::clamp(nsb, params.minBits, params.maxBits);
>       |                               ~~~~~^
> ```

Solved by returning to using pathing for `gcc-9.2.0` for `C++` libraries / headers (had been trying `v14.2.0`).

**Comment by rickgrubin-tomorrow** [comment]
On **hera**:

`spack-stack/configs/sites/tier1/hera/compilers.yaml`

```
compilers:
- compiler:
    spec: oneapi@=2024.2.1
    paths:
      cc: /apps/oneapi/compiler/2024.2/bin/icx
      cxx: /apps/oneapi/compiler/2024.2/bin/icpx
      f77: /apps/oneapi/compiler/2024.2/bin/ifx
      fc: /apps/oneapi/compiler/2024.2/bin/ifx
    flags: {}
    operating_system: rocky8
    modules:
    - intel/2024.2.1
    environment:
      prepend_path:
        PATH: '/apps/gnu/gcc-9.2.0/bin'
        LD_LIBRARY_PATH: '/apps/gnu/gcc-9.2.0/lib64'
        CPATH: '/apps/gnu/gcc-9.2.0/include'
```

and the packages noted in [Unified environment build errors with ifx #1279](https://github.com/JCSDA/spack-stack/issues/1279) -- `gfsio` | `landsfcutil` | `sfcio` | `sigio` -- updated to reflect versions that build with `ifx`, `spack-stack@1.8.0` successfully builds; it does so, however, with some duplicates (20 of them), all of which concretize identically excepting their hash:

```
base-env@1.0.0%oneapi@2024.2.1  build_system=bundle  arch=linux-rocky8-haswell
bufr-query@0.0.2%oneapi@2024.2.1~ipo+python  build_system=cmake  build_type=Release  generator=make  patches=3ae2f2f  arch=linux-rocky8-haswell
crtm@v2.4.1-jedi%oneapi@2024.2.1+fix~ipo  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
crtm@2.4.0.1%oneapi@2024.2.1+fix~ipo  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
esmf@8.6.1%oneapi@2024.2.1~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf+shared~xerces  build_system=makefile  esmf_comm=auto  esmf_os=auto  esmf_pio=auto  patches=f63d405  snapshot=none  arch=linux-rocky8-haswell
esmf@8.7.0b11%oneapi@2024.2.1~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf+shared~xerces  build_system=makefile  esmf_comm=auto  esmf_os=auto  esmf_pio=auto  patches=f63d405  snapshot=b11  arch=linux-rocky8-haswell fms@2024.02%oneapi@2024.2.1+deprecated_io+gfs_phys+internal_file_nml~ipo~large_file+openmp+pic+quad_precision~shared~yaml  build_system=cmake  build_type=Release  constants=GFS  generator=make  patches=2b12a6c  precision=32,64  arch=linux-rocky8-haswell
gsibec@1.2.1%oneapi@2024.2.1~ipo~mkl  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell hdf5@1.14.3%oneapi@2024.2.1~cxx+fortran+hl~ipo~java~map+mpi+shared~subfiling~szip+threadsafe+tools  api=default  build_system=cmake  build_type=Release  generator=make  patches=82088c8  arch=linux-rocky8-haswell
jedi-base-env@1.0.0%oneapi@2024.2.1+bufrquery+fftw+hdf4  build_system=bundle  arch=linux-rocky8-haswell
mapl@2.46.3%oneapi@2024.2.1~debug+extdata2g~f2py+fargparse~ipo+pflogger~pfunit~shared  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
nccmp@1.9.0.1%oneapi@2024.2.1~ipo  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
nco@5.1.6%oneapi@2024.2.1~doc  build_system=autotools  arch=linux-rocky8-haswell
ncview@2.1.9%oneapi@2024.2.1  build_system=autotools  arch=linux-rocky8-haswell
netcdf-c@4.9.2%oneapi@2024.2.1+blosc~byterange+dap~fsync~hdf4~jna~logging+mpi~nczarr_zip+optimize~parallel-netcdf+pic+shared~szip+zstd  build_system=autotools  patches=0161eb8  arch=linux-rocky8-haswell
netcdf-cxx4@4.3.1%oneapi@2024.2.1~doc+pic+shared  build_system=autotools  arch=linux-rocky8-haswell
netcdf-fortran@4.6.1%oneapi@2024.2.1~doc+pic+shared  build_system=autotools  arch=linux-rocky8-haswell
parallelio@2.6.2%oneapi@2024.2.1+fortran~ipo~logging+mpi~ncint+pnetcdf+shared~timing  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
py-h5py@3.11.0%oneapi@2024.2.1~mpi  build_system=python_pip  arch=linux-rocky8-haswell
py-netcdf4@1.5.8%oneapi@2024.2.1~mpi  build_system=python_pip  patches=255b5ae  arch=linux-rocky8-haswell
ufs-pyenv@1.0.0%oneapi@2024.2.1  build_system=bundle  arch=linux-rocky8-haswell
```

so modules can't be refreshed and a valid set of stack modules can't be created.

I've not encountered this before, and don't know where to start looking.

[ And in the event it's relevant, the entire stack builds with `ifort` as well, with the same duplicates issue ]

**Comment by ulmononian** [comment]
great progress, @rickgrubin-noaa. @RatkoVasic-NOAA @AlexanderRichert-NOAA @climbfuji any idea why these package duplicates would be happening?

**Comment by rickgrubin-noaa** [comment]
> great progress, @rickgrubin-noaa. @RatkoVasic-NOAA @AlexanderRichert-NOAA @climbfuji any idea why these package duplicates would be happening?

Ref. this [comment above](https://github.com/JCSDA/spack-stack/issues/1345#issuecomment-2465520029), containing a list of duplicates:

Trying to track this down using `spack find -N` in an activated / fully built env, and looking at, for example, `hdf5@1.14.3`

```
% file hdf5*
hdf5-1.14.3-7jz6yub: setgid, directory
hdf5-1.14.3-rvoosit: setgid, directory
```

Within each of those installed directories, looking at the file `.spack/spack-build-env.txt`, the only differences are:

```
arch=linux-rocky8-haswell/7jz6yub
arch=linux-rocky8-haswell/rvoosit
```

As one would expect, `rocky8` is specified in various files under the configs directory, when specifying a host's underlying OS, e.g.

```
sites/tier1/hera/compilers.yaml:    operating_system: rocky8
```

The tag `haswell` shows up in one place: 

```
./sites/tier1/hera/packages.yaml:    target: [haswell]
```

@climbfuji @AlexanderRichert-NOAA @RatkoVasic-NOAA  -- any thoughts on how this occurs / where to start looking?

**Comment by rickgrubin-noaa** [comment]
```
% spack diff /7jz6yub /rvoosit
==> Warning: This interface is subject to change.

--- hdf5@1.14.3/7jz6yubonaibnjtujho7dqaznnvter5u
+++ hdf5@1.14.3/rvoosittc42optuwucdyxjzo5rcldz6p
@@ hash @@
- hdf5 7jz6yubonaibnjtujho7dqaznnvter5u
+ hdf5 rvoosittc42optuwucdyxjzo5rcldz6p
@@ virtual_node @@
+ fortran-rt
@@ virtual_on_edge @@
+ hdf5 intel-oneapi-runtime fortran-rt
@@ virtual_on_incoming_edges @@
+ intel-oneapi-runtime fortran-rt
```


 After saving the output of each of `spack spec hdf5 /7jz6yub` and `spack spec hdf5 /rvoosit`

```
% diff 7jz6yub rvoosit
3c3
< -  hdf5/7jz6yub
---
> -  hdf5/rvoosit
16d15
< [+]   ^gcc-runtime@9.2.0%gcc@9.2.0 build_system=generic arch=linux-rocky8-haswell
20a20
> [+]     ^gcc-runtime@9.2.0%gcc@9.2.0 build_system=generic arch=linux-rocky8-haswell
```

so in one case, `gcc-runtime` is its own dependency, and in another case, it's a dependent of something else.

For hash `/7jz6yub`:

```
[+]   ^gcc-runtime@9.2.0%gcc@9.2.0 build_system=generic arch=linux-rocky8-haswell
[...]
[+]   ^intel-oneapi-runtime@2024.2.1%oneapi@2024.2.1 build_system=generic arch=linux-rocky8-haswell
```

and for hash `/rvoosit`:

```
[+]   ^intel-oneapi-runtime@2024.2.1%oneapi@2024.2.1 build_system=generic arch=linux-rocky8-haswell
[+]     ^gcc-runtime@9.2.0%gcc@9.2.0 build_system=generic arch=linux-rocky8-haswell
```

In looking at some of the other duplicates, they have a dependency on `hdf5` in one form or another, and some exhibit the dependency interplay between `intel-oneapi-runtime` and `gcc-runtime`, some do not.

**Comment by rickgrubin-noaa** [comment]
Per @climbfuji 's [suggestion](https://jcsda.slack.com/archives/C04D6ALT0SX/p1731469746568329), attached is `log.concretize`, and `spack.yaml` (each slightly renamed to conform to github's filename upload rules).

See also [this comment](https://spackpm.slack.com/archives/CMHK7MF51/p1731487977990969?thread_ts=1731436974.315049&cid=CMHK7MF51) from the spack slack channel.

[log-concretize.txt](https://github.com/user-attachments/files/17736236/log-concretize.txt)
[spack-yaml.txt](https://github.com/user-attachments/files/17736248/spack-yaml.txt)

**Comment by climbfuji** [comment]
You should declare the intel-oneapi-runtime package as an external package (since you declare the compiler and MPI library as external, too). Several tier1 or tier2 site configs do have this setting already, please check.

**Comment by rickgrubin-noaa** [comment]
> You should declare the intel-oneapi-runtime package as an external package (since you declare the compiler and MPI library as external, too). Several tier1 or tier2 site configs do have this setting already, please check.

`intel-oneapi-runtime` added as an external in `packages_oneapi.yaml` per the _**nautilus**_ config (the only `tier1` host which specifies this).

```
$SPACK_STACK_DIR/util/show_duplicate_packages.py -d envs/unified-dev.hera.oneapi-ifort/log.concretize 
p4yjfrb  crtm@v2.4.1-jedi%oneapi@2024.2.1+fix~ipo  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
gqra4zu  crtm@v2.4-jedi.2%oneapi@2024.2.1+fix~ipo  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
74cux3x  crtm@2.4.0.1%oneapi@2024.2.1+fix~ipo  build_system=cmake  build_type=Release  generator=make  arch=linux-rocky8-haswell
jlb2o5n  esmf@8.7.0b11%oneapi@2024.2.1~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf+shared~xerces  build_system=makefile  esmf_comm=auto  esmf_os=auto  esmf_pio=auto  patches=f63d405  snapshot=b11  arch=linux-rocky8-haswell
gylhdlc  esmf@8.6.1%oneapi@2024.2.1~debug~external-lapack+external-parallelio+mpi+netcdf~pnetcdf+shared~xerces  build_system=makefile  esmf_comm=auto  esmf_os=auto  esmf_pio=auto  patches=f63d405  snapshot=none  arch=linux-rocky8-haswell
===
Duplicates found!
```

Safe to assume that, given different package versions, this is acceptable?

`crtm@2.4.0.1 /74cux3x` appears standalone, and in `global-workflow-env` / `gsi-env` / `soca-env` / `ufs-weather-model-env` at that hash, so seems OK.

**Comment by climbfuji** [comment]
This looks promising. We do need two different ESMF versions and three different CRTM versions at the moment

**Comment by rickgrubin-noaa** [comment]
Adding `intel-oneapi-runtime` as an external (as with the compiler and MPI specs) to `packages_oneapi.yaml`, e.g.

```
  intel-oneapi-runtime:
    externals:
    - spec: intel-oneapi-runtime@2024.2.1%oneapi@2024.2.1
      prefix: /apps/oneapi/compiler/2024.2 
      modules:
      - compiler-rt/2024.2.1
```
    
resolves duplicates and envs build successfully.

**Comment by rickgrubin-noaa** [comment]
**_hera_**

```
% ls /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-llvm/envs
ue-llvm-ifort-2024.2.1 
ue-llvm-ifx-2024.2.1
```

**`ifx`**

```
% module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-llvm/envs/ue-llvm-ifx-2024.2.1/install/modulefiles/Core
% module load stack-oneapi/2024.2.1
% module load stack-intel-oneapi-mpi/2021.13
```

----

**`ifort`**

```
% module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.8.0-llvm/envs/ue-llvm-ifort-2024.2.1/install/modulefiles/Core
% module load stack-oneapi/2024.2.1
% module load stack-intel-oneapi-mpi/2021.13
```

**Comment by climbfuji** [comment]
Done!

**Comment by uturuncoglu** [comment]
@climbfuji @rickgrubin-noaa I know this is closed but I have similar issue with hdf5 and still adds gcc-runtime on Derecho. I also add compiler, mpi and also intel-runtime but no help. At this point, i am chaining existing installation (/glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.9.1/envs/ue-oneapi-2024.2.1/install) to extend it with additional libraries. I wonder if you have any other suggestion.
