### ISSUE TITLE
narwhal ssl issue

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#870]
**Describe the bug**

Using /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.0/envs/unified-env-intel-2021.4.0 on narwhal I am getting this error.

>>> import ioda_conv_engines as iconv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/work2/reinecke/cylc-run/oct2021-drE20P4-1.4.1-nar/share/static/lib/python3.10/pyiodaconv/ioda_conv_engines.py", line 3, in <module>
    from pyioda import ioda_obs_space as ioda_os
  File "/p/work2/reinecke/cylc-run/oct2021-drE20P4-1.4.1-nar/share/static/lib/python3.10/pyioda/ioda_obs_space/__init__.py", line 4, in <module>
    from pyioda import ioda
  File "/p/work2/reinecke/cylc-run/oct2021-drE20P4-1.4.1-nar/share/static/lib/python3.10/pyioda/ioda/__init__.py", line 8, in <module>
    from ._ioda_python import *
ImportError: /usr/lib64/libssh.so.4: undefined symbol: EVP_KDF_CTX_new_id, version OPENSSL_1_1_1d

**To Reproduce**

See above

**Expected behavior**

Do not expect the get errors.

**System:**

Narwhal

**Additional context**

**Comment by areinecke** [comment]
Note that this works if I use /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1 instead of /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.0 at run time, however, when building with /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1 I get the following error during the build of ioda:

> /p/home/reinecke/neptune-bundle8/src/ioda/src/distribution/AtlasDistribution.cc(66): error: class "atlas::mesh::detail::MeshImpl" has no member "nb_partitions"
>     if (static_cast<size_t>(mesh_->nb_partitions()) != atlas::mpi::comm().size()) {
>                                    ^
>  
> /p/home/reinecke/neptune-bundle8/src/ioda/src/distribution/AtlasDistribution.cc(68): error: class "atlas::mesh::detail::MeshImpl" has no member "nb_partitions"
>       msg << "The number of mesh partitions, " << mesh_->nb_partitions()

This is fixed by using ecmwf-atlas/0.34.0 (which is in 1.5.0) instead of ecmwf-atlas/0.35.0 (which is in 1.5.1)

**Comment by climbfuji** [comment]
Is your neptune bundle up to date with the latest JEDI develop? I'd prefer not having to fix spack-stack-1.5.0, if possible (there were some issues that forced us to change things around openssl, openssh etc in spack-stack-1.5.1 that apparently fixed that issue). The current jedi-bundle develop works with spack-stack-1.5.1.

**Comment by areinecke** [comment]
Sarah would have to answer where we are relative to JEDI develop.  If we're not up to date, part of the reason might be that I don't have access to any of the JEDI repos anymore.

**Comment by climbfuji** [comment]
> Sarah would have to answer where we are relative to JEDI develop. If we're not up to date, part of the reason might be that I don't have access to any of the JEDI repos anymore.

You do if you accept the invite I sent you Monday :-)

**Comment by areinecke** [comment]
I replied that I never got the invite.

**Comment by climbfuji** [comment]
> I replied that I never got the invite.

That's very annoying. Let me cancel the invitation and resend it right now.

**Comment by climbfuji** [comment]
Done:
> You've invited Alex Reinecke to JCSDA-internal! They'll be receiving an email shortly. They can also visit https://github.com/JCSDA-internal to accept the invitation.

**Comment by areinecke** [comment]
Was able to get to the through the link.  Thanks.

**Comment by climbfuji** [comment]
I am wondering why the 1.5.0 issue is coming up now, is that because of the Narwhal sys update? Or have you been using an older version until now and 1.5.0 never worked?

**Comment by areinecke** [comment]
I think we have been using an older version.

**Comment by climbfuji** [comment]
Let me check if there's a simple workaround for 1.5.0. With Intel I suppose?

**Comment by areinecke** [comment]
Yes, with Intel.  But stand-by because now that I have access Sarah is able to update the code.

**Comment by climbfuji** [comment]
Turns out there's no simple workaround for 1.5.0. I could rebuild, but I am going to wait if 1.5.1 works for you or not.

**Comment by areinecke** [comment]
Is there any update on this?  last I heard was that you were going to rebuild.

**Comment by climbfuji** [comment]
Nope, I was waiting to hear back if 1.5.1 works or not (see https://github.com/JCSDA/spack-stack/issues/870#issuecomment-1804748646).

**Comment by areinecke** [comment]
According to Sarah it's not, she said something about not being ready to upgrade to skywalker 6 or something.

**Comment by climbfuji** [comment]
> According to Sarah it's not, she said something about not being ready to upgrade to skywalker 6 or something.

I assume you mean Skylab v6 ;-) I didn't get that information (or I missed it). I'll start the rebuild asap.

**Comment by climbfuji** [comment]
@areinecke  I rebuilt spack-stack 1.5.0 with Intel and verified that the problem described above is gone. I am also rebuilding with GNU now and will let you know when that's done. Can you try with 1.5.0 intel in the meanwhile please?

**Comment by climbfuji** [comment]
GNU stack is done, too (but I didn't run any tests with it).

**Comment by areinecke** [comment]
Thanks, Dom.  I'll check the build and test.

**Comment by climbfuji** [comment]
@sking112 @areinecke Did you have a chance to test the newly built spack-stack-1.5.0 stack? Is it working?

**Comment by sking112** [comment]
Hi @climbfuji. I was able to build. I'm in the middle of testing running but that has been slow going because of the Narwhal queues.

**Comment by climbfuji** [comment]
@areinecke Following up on this, are the SSL issues resolved on Narwhal with the rebuilt spack-stack?

**Comment by climbfuji** [comment]
I'll go ahead and close this as completed. If there's still a problem, please reopen or open a new issue as needed. Thanks!
