### ISSUE TITLE
ecflow@5.11.4 also does not build with gcc@9.4.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1009]
**Describe the bug**
Container build of `ecflow@5.11.4` with `gcc@9.4.0` fails in the same way as it did for the Intel Classic compilers (see https://github.com/JCSDA/spack-stack/issues/1001):
```
#17 4758.7   >> 1129    /tmp/root/spack-stage/spack-stage-ecflow-5.11.4-btgdenffmmx7bi7odm
#17 4758.7              bl2xnq2ojwfvpf/spack-src/Base/src/cts/CtsApi.cpp:834:13: error: 'a
#17 4758.7              ssert' was not declared in this scope
```

**To Reproduce**
Build `ubuntu-gcc-openmpi` container with `jedi-ci` specs in CI using branch `feature/discover_scu17`.

Also in CI for clang: https://github.com/JCSDA/spack-stack/actions/runs/7990666964/job/21819977664

**Expected behavior**
It builds!

**System:**
See above

**Additional context**
n/a
